/*
Copyright (c) 2012, University of Texas at El Paso
All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:

	-Redistributions of source code must retain the above copyright notice, this list of conditions
	 and the following disclaimer.
	-Redistributions in binary form must reproduce the above copyright notice, this list of conditions
	 and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.*/


/*
Copyright (c) 2012, University of Texas at El Paso
All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:

	-Redistributions of source code must retain the above copyright notice, this list of conditions
	 and the following disclaimer.
	-Redistributions in binary form must reproduce the above copyright notice, this list of conditions
	 and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.*/


package edu.utep.trustlab.visko.planning;

import java.util.*;

import com.hp.hpl.jena.query.ResultSet;

import edu.utep.trustlab.visko.util.ResultSetToVector;
import edu.utep.trustlab.visko.sparql.ViskoTripleStore;

public class OperatorPath extends Vector<String> {
	//the viewer that consumes the visualization generated by this pipeline
	private String viewerURI;
	
	//the view this operator pipeline generates
	private String viewURI;
	
	//the triple store instance this operator relies on
	private ViskoTripleStore ts;
	
	private boolean containsDataFilter;
	private boolean containsDimensionFilter;
	private boolean containsViewMapper;
	private boolean containsInterpolator;
	
	private boolean violatesRuleSingleDataFilter;
	private boolean violatesRuleSingleDimensionFilter;
	private boolean violatesRuleSingleViewMapper;
	private boolean violatesRuleSingleInterpolator;
	
	public OperatorPath(String viewerURI) {
		super();
		this.viewerURI = viewerURI;
	}
	
	public OperatorPath(ViskoTripleStore tripleStore) {
		super();
		ts = tripleStore;
	}
	
	public void set(Vector<String> operatorURIs) {
		for (String operatorURI : operatorURIs)
			add(operatorURI);
	}
	
	public boolean containsViewMapper(){
		return containsViewMapper;
	}

	public boolean containsDataFilter(){
		return containsDataFilter;
	}

	public boolean containsDimensionFilter(){
		return containsDimensionFilter;
	}
	
	public boolean containsInterpolator(){
		return containsInterpolator;
	}

	private boolean isAlreadyInPath(String operatorURI){		
		for(String anOperatorURI : this)
			if(operatorURI.equals(anOperatorURI))
				return true;
		return false;
	}
	
	public boolean generatesView(String aViewURI){
		if(viewURI != null && aViewURI != null)
			return viewURI.equals(aViewURI);
		
		return false;
	}
		
	public boolean outputCanBeViewedByViewerSet(String viewerSetURI){
		String finalOperatorURI = this.lastElement();
		if(ts.outputCanBeViewedByViewerSet(finalOperatorURI, viewerSetURI)){
			setTargetViewerFromViewerSet(viewerSetURI);
			return true;
		}
		
		return false;
	}
	
	private void setTargetViewerFromViewerSet(String viewerSetURI){
		String finalOperatorURI = this.lastElement();
		ResultSet viewerResults = ts.getTargetViewerForOperator(finalOperatorURI, viewerSetURI);
		Vector<String> viewerURIs = ResultSetToVector.getVectorFromResultSet(viewerResults, "viewer");
		viewerURI = viewerURIs.firstElement();
	}
	
	public OperatorPath clonePath(){
		OperatorPath clonedPath = new OperatorPath(ts);
		
		for(String operatorURI : this)
			clonedPath.add(operatorURI);
		
		clonedPath.setViewURI(viewURI);
		clonedPath.setViewerURI(viewerURI);
		
		return clonedPath;
	}
	
	public Vector<String> filterOperatorsAlreadyInPath(Vector<String> operatorURIs){
		Vector<String> eligibleOperatorURIs = new Vector<String>();
		
		for(String potentialEligibleOperatorURI : operatorURIs)
			if(!isAlreadyInPath(potentialEligibleOperatorURI))
				eligibleOperatorURIs.add(potentialEligibleOperatorURI);		
		return eligibleOperatorURIs;
	}
	
	public boolean add(String operatorURI){
		 if(ts.isViewMapper(operatorURI)){
			 if(containsViewMapper)
				 violatesRuleSingleViewMapper = true;
			 else containsViewMapper = true;
			 setViewGeneratedByViewMapper(operatorURI);
		 }
		 else if(ts.isDataFilter(operatorURI))
			 if(containsDataFilter)
				 violatesRuleSingleDataFilter = true;
			 else
				 containsDataFilter = true;
		 else if(ts.isDimensionFilter(operatorURI))
			 if(containsDimensionFilter)
				 violatesRuleSingleDimensionFilter = true;
			 else
				 containsDimensionFilter = true;
		 else if(ts.isInterpolator(operatorURI))
			 if(containsInterpolator)
				 violatesRuleSingleInterpolator = true;
			 else
				 containsInterpolator = true;

		 return super.add(operatorURI);
	}
	
	public boolean violatesRules(){
		return violatesRuleSingleDataFilter
				|| violatesRuleSingleDimensionFilter
				|| violatesRuleSingleInterpolator
				|| violatesRuleSingleViewMapper;
	}
	
	private void setViewGeneratedByViewMapper(String viewMapperURI){
		Vector<String> view = ResultSetToVector.getVectorFromResultSet(ts.getViewGeneratedByMapper(viewMapperURI), "view");
		viewURI = view.firstElement(); 
	}
	
	public boolean violatesRequestedView(String requestedViewURI){
		if(viewURI != null && !requestedViewURI.equals(viewURI))
			return true;
		return false;
	}
		
	public String getViewGenerated(){
		return viewURI;
	}
	
	public boolean isEmptyPath() {
		return size() == 0;
	}
	
	private void setViewURI(String aViewURI){
		viewURI = aViewURI;
	}
	
	private void setViewerURI(String aViewerURI){
		viewerURI = aViewerURI;
	}

	public String getViewerURI() {
		return viewerURI;
	}
	
	public String toString(){
		String stringRepresentation = 
				"Operator path:\n"
				+ super.toString() + "\n"
				+ "Viewer: " + this.viewerURI;
		return stringRepresentation;
	}
}