/*
Copyright (c) 2012, University of Texas at El Paso
All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:

	-Redistributions of source code must retain the above copyright notice, this list of conditions
	 and the following disclaimer.
	-Redistributions in binary form must reproduce the above copyright notice, this list of conditions
	 and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.*/


/*
Copyright (c) 2012, University of Texas at El Paso
All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted
provided that the following conditions are met:

	-Redistributions of source code must retain the above copyright notice, this list of conditions
	 and the following disclaimer.
	-Redistributions in binary form must reproduce the above copyright notice, this list of conditions
	 and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.*/


package edu.utep.trustlab.visko.planning;

import java.util.*;

import com.hp.hpl.jena.query.ResultSet;

import edu.utep.trustlab.visko.util.ResultSetToVector;
import edu.utep.trustlab.visko.sparql.ViskoTripleStore;

public class OperatorPath extends Vector<String> {
	//the viewer that consumes the visualization generated by this pipeline
	private String viewerURI;
	
	//the view this operator pipeline generates
	private String viewURI;
	
	//the triple store instance this operator relies on
	private ViskoTripleStore ts;
	
	//hashmap to quickly check for operator membership
	private HashMap<String, Boolean> operatorLookup;
	
	private boolean containsDataFilter;
	private boolean containsDimensionFilter;
	private boolean containsViewMapper;
	private boolean containsInterpolator;
	
	private boolean violatesRuleSingleDataFilter;
	private boolean violatesRuleSingleDimensionFilter;
	private boolean violatesRuleSingleViewMapper;
	private boolean violatesRuleSingleInterpolator;
	
	public OperatorPath(String aViewerURI) {
		super();
		viewerURI = aViewerURI;
		operatorLookup = new HashMap<String, Boolean>();
	}
	
	public OperatorPath(ViskoTripleStore tripleStore) {
		super();
		ts = tripleStore;
		operatorLookup = new HashMap<String, Boolean>();
	}
	
	public void set(Vector<String> operatorURIs) {
		for (String operatorURI : operatorURIs)
			add(operatorURI);
	}
	
	public boolean containsViewMapper(){
		return containsViewMapper;
	}

	public boolean containsDataFilter(){
		return containsDataFilter;
	}

	public boolean containsDimensionFilter(){
		return containsDimensionFilter;
	}
	
	public boolean containsInterpolator(){
		return containsInterpolator;
	}

	private boolean isAlreadyInPath(String operatorURI){
		Boolean value = operatorLookup.get(operatorURI);
		if(value != null && value.booleanValue())
			return true;
		return false;
	}
	
	public boolean generatesView(String aViewURI){
		if(viewURI != null && aViewURI != null)
			return viewURI.equals(aViewURI);
		
		return false;
	}
	
	public String outputCanBeViewedByViewerSet(Vector<String> viewerURIs){
		String finalOperatorURI = this.lastElement();
		for(String aViewerURI : viewerURIs){
			if(ts.outputCanBeViewedByViewer(finalOperatorURI, aViewerURI)){
				return aViewerURI;
			}
		}
		return null;
	}
		
	public void setViewer(String aViewerURI){
		viewerURI = aViewerURI;
	}
	
	public OperatorPath clonePath(){

		@SuppressWarnings("unchecked")
		Vector<String> operatorURIs = (Vector<String>)clone();
		
		OperatorPath clonedPath = new OperatorPath(ts);
		clonedPath.set(operatorURIs);		
		clonedPath.setViewURI(viewURI);
		clonedPath.setViewerURI(viewerURI);
		
		return clonedPath;
	}
	
	public Vector<String> filterOperatorsAlreadyInPath(Vector<String> operatorURIs){
		Vector<String> eligibleOperatorURIs = new Vector<String>();
		
		for(String potentialEligibleOperatorURI : operatorURIs)
			if(!isAlreadyInPath(potentialEligibleOperatorURI))
				eligibleOperatorURIs.add(potentialEligibleOperatorURI);		
		return eligibleOperatorURIs;
	}
	
	public boolean add(String operatorURI){
		 if(ts.isViewMapper(operatorURI)){
			 violatesRuleSingleViewMapper = containsViewMapper;
			 containsViewMapper = true;
			 setViewGeneratedByViewMapper(operatorURI);
		 }
		 else if(ts.isDataFilter(operatorURI)){
			 violatesRuleSingleDataFilter = containsDataFilter;
			 containsDataFilter = true;
		 }
		 else if(ts.isDimensionFilter(operatorURI)){
			violatesRuleSingleDimensionFilter = containsDimensionFilter;		
		 	containsDimensionFilter = true;
		 }
		 else if(ts.isInterpolator(operatorURI)){
			 violatesRuleSingleInterpolator = containsInterpolator;
			 containsInterpolator = true;
		 }
		 
		 operatorLookup.put(operatorURI, new Boolean(true));
		 return super.add(operatorURI);
	}
	
	public boolean violatesRules(){
		return violatesRuleSingleDataFilter
				|| violatesRuleSingleDimensionFilter
				|| violatesRuleSingleInterpolator
				|| violatesRuleSingleViewMapper;
	}
	
	private void setViewGeneratedByViewMapper(String viewMapperURI){
		Vector<String> view = ResultSetToVector.getVectorFromResultSet(ts.getViewGeneratedByViewMapper(viewMapperURI), "view");
		viewURI = view.firstElement(); 
	}
	
	public boolean violatesRequestedView(String requestedViewURI){
		if(viewURI != null && requestedViewURI != null && !requestedViewURI.equals(viewURI))
			return true;
		return false;
	}
		
	public String getViewGenerated(){
		return viewURI;
	}
	
	private void setViewURI(String aViewURI){
		viewURI = aViewURI;
	}
	
	private void setViewerURI(String aViewerURI){
		viewerURI = aViewerURI;
	}

	public String getViewerURI() {
		return viewerURI;
	}
	
	public String toString(){
		String stringRepresentation = 
				"Operator path:\n"
				+ super.toString() + "\n"
				+ "Viewer: " + this.viewerURI;
		return stringRepresentation;
	}
}